/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Dialog: typeof import('./src/components/dialog/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    LoginDialog: typeof import('./src/plugin/loginDialogPlugin/loginDialog.vue')['default']
    LoginModal: typeof import('./src/components/login/loginModal.vue')['default']
    Password: typeof import('./src/components/login/components/password.vue')['default']
    Phone: typeof import('./src/components/login/components/phone.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SlideSplit: typeof import('./src/components/login/SlideSplit/index.vue')['default']
    Wechat: typeof import('./src/components/login/components/wechat.vue')['default']
  }
}
